name: projeto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  convert: ^3.1.2
  flutter:
    sdk: flutter
  form_builder_image_picker: ^4.1.0
  foundation: ^0.0.5
  go_router: ^14.6.2
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5
  universal_html: ^2.2.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
